// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // BatchInvoiceItem
    public class BatchInvoiceItem
    {
        public Guid Id { get; set; } // PrimaryKey (Primary key)
        public Guid BatchInvoiceId { get; set; } // BatchInvoiceId
        public Guid InvoiceId { get; set; } // InvoiceId

        // Foreign keys

        /// <summary>
        /// Parent BatchInvoice pointed by [BatchInvoiceItem].([BatchInvoiceId]) (FK_dbo.BatchInvoiceItem_dbo.BatchInvoice_BatchInvoiceId)
        /// </summary>
        public BatchInvoice BatchInvoice { get; set; } // FK_dbo.BatchInvoiceItem_dbo.BatchInvoice_BatchInvoiceId

        /// <summary>
        /// Parent Invoice pointed by [BatchInvoiceItem].([InvoiceId]) (FK_dbo.BatchInvoiceItem_dbo.Invoice_InvoiceId)
        /// </summary>
        public Invoice Invoice { get; set; } // FK_dbo.BatchInvoiceItem_dbo.Invoice_InvoiceId
    }

}
// </auto-generated>
