// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Invoice
    public class Invoice
    {
        public Guid Id { get; set; } // PrimaryKey (Primary key)
        public decimal Net { get; set; } // Net
        public decimal Gross { get; set; } // Gross
        public decimal Tax { get; private set; } // Tax

        // Reverse navigation

        /// <summary>
        /// Child BatchInvoiceItems where [BatchInvoiceItem].[InvoiceId] point to this entity (FK_dbo.BatchInvoiceItem_dbo.Invoice_InvoiceId)
        /// </summary>
        public ICollection<BatchInvoiceItem> BatchInvoices { get; set; } // BatchInvoiceItem.FK_dbo.BatchInvoiceItem_dbo.Invoice_InvoiceId

        /// <summary>
        /// Child InvoiceItems where [InvoiceItem].[InvoiceId] point to this entity (FK_dbo.InvoiceItem_dbo.Invoice_InvoiceId)
        /// </summary>
        public ICollection<InvoiceItem> Journals { get; set; } // InvoiceItem.FK_dbo.InvoiceItem_dbo.Invoice_InvoiceId
        public Invoice()
        {
            BatchInvoices = new List<BatchInvoiceItem>();
            Journals = new List<InvoiceItem>();
        }
    }

}
// </auto-generated>
