// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Journal
    public class Journal
    {
        public Guid Id { get; set; } // PrimaryKey (Primary key)

        // Reverse navigation

        /// <summary>
        /// Child InvoiceItems where [InvoiceItem].[JournalId] point to this entity (FK_dbo.InvoiceItem_dbo.Journal_JournalId)
        /// </summary>
        public ICollection<InvoiceItem> InvoiceItems { get; set; } // InvoiceItem.FK_dbo.InvoiceItem_dbo.Journal_JournalId

        public Journal()
        {
            InvoiceItems = new List<InvoiceItem>();
        }
    }

}
// </auto-generated>
