// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Course
    public class Course
    {
        public int CourseId { get; set; } // CourseID (Primary key)
        public string Title { get; set; } // Title
        public int Credits { get; set; } // Credits
        public int DepartmentId { get; set; } // DepartmentID

        // Reverse navigation

        /// <summary>
        /// Child CourseInstructors where [CourseInstructor].[CourseID] point to this entity (FK_dbo.CourseInstructor_dbo.Course_CourseID)
        /// </summary>
        public ICollection<CourseInstructor> CourseInstructors { get; set; } // CourseInstructor.FK_dbo.CourseInstructor_dbo.Course_CourseID

        [NotMapped]
        public List<Instructor> Instructors
        {
            get
            {
                return CourseInstructors.Select(i => i.Instructor).ToList();
            }
        }
        // Foreign keys

        /// <summary>
        /// Parent Department pointed by [Course].([DepartmentId]) (FK_dbo.Course_dbo.Department_DepartmentID)
        /// </summary>
        public Department Department { get; set; } // FK_dbo.Course_dbo.Department_DepartmentID

        public Course()
        {
            CourseInstructors = new List<CourseInstructor>();
        }
    }

}
// </auto-generated>
