// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // CourseInstructor
    public class CourseInstructor
    {
        public int CourseId { get; set; } // CourseID (Primary key)
        public int InstructorId { get; set; } // InstructorID (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent Course pointed by [CourseInstructor].([CourseId]) (FK_dbo.CourseInstructor_dbo.Course_CourseID)
        /// </summary>
        public Course Course { get; set; } // FK_dbo.CourseInstructor_dbo.Course_CourseID

        /// <summary>
        /// Parent Instructor pointed by [CourseInstructor].([InstructorId]) (FK_dbo.CourseInstructor_dbo.Instructor_InstructorID)
        /// </summary>
        public Instructor Instructor { get; set; } // FK_dbo.CourseInstructor_dbo.Instructor_InstructorID
    }

}
// </auto-generated>
