// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Course
    public class Course
    {
        public int CourseId { get; set; } // CourseID (Primary key)
        public string Title { get; set; } // Title
        public int Credits { get; set; } // Credits
        public int DepartmentId { get; set; } // DepartmentID

        // Reverse navigation
        public ICollection<Instructor> Instructors { get; set; }

        // Foreign keys
        public Department Department { get; set; }

        public Course()
        {
            Instructors = new HashSet<Instructor>();
        }
    }
}
// </auto-generated>
