// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Department
    public class Department
    {
        public int DepartmentId { get; set; } // DepartmentID (Primary key)
        public string Name { get; set; } // Name
        public decimal Budget { get; set; } // Budget
        public int? Administrator { get; set; } // Administrator

        // Reverse navigation

        /// <summary>
        /// Child Courses where [Course].[DepartmentID] point to this entity (FK_dbo.Course_dbo.Department_DepartmentID)
        /// </summary>
        public ICollection<Course> Courses { get; set; } // Course.FK_dbo.Course_dbo.Department_DepartmentID

        public Department()
        {
            Courses = new List<Course>();
        }
    }

}
// </auto-generated>
