// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Instructor
    public class Instructor
    {
        public int InstructorId { get; set; } // InstructorID (Primary key)
        public string LastName { get; set; } // LastName
        public string FirstName { get; set; } // FirstName
        public DateTime HireDate { get; set; } // HireDate
        public string FullName { get; private set; } // FullName

        // Reverse navigation
        public ICollection<Course> Courses { get; set; }
        public OfficeAssignment OfficeAssignment { get; set; }

        public Instructor()
        {
            Courses = new List<Course>();
        }
    }
}
// </auto-generated>
