// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // OfficeAssignment
    public class OfficeAssignment
    {
        public int InstructorId { get; set; } // InstructorID (Primary key)
        public string Location { get; set; } // Location
        public byte[] Timestamp { get; set; } // Timestamp

        // Foreign keys

        /// <summary>
        /// Parent Instructor pointed by [OfficeAssignment].([InstructorId]) (FK_dbo.OfficeAssignment_dbo.Instructor_InstructorID)
        /// </summary>
        public Instructor Instructor { get; set; } // FK_dbo.OfficeAssignment_dbo.Instructor_InstructorID
    }

}
// </auto-generated>
