// <auto-generated />
namespace Tanneryd.BulkOperations.EF6.Tests.Migrations.Invoice
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class AddComputedTaxColumnToInvoice : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddComputedTaxColumnToInvoice));
        
        string IMigrationMetadata.Id
        {
            get { return "202002251520286_AddComputedTaxColumnToInvoice"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
