// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Coordinate
    public class Coordinate
    {
        public int Id { get; set; } // Id (Primary key)
        public int Value { get; set; } // Value

        // Reverse navigation

        /// <summary>
        /// Child Points where [Point].[XCoordinateId] point to this entity (FK_dbo.Point_dbo.Coordinate_XCoordinateId)
        /// </summary>
        public ICollection<Point> Points_XCoordinateId { get; set; } // Point.FK_dbo.Point_dbo.Coordinate_XCoordinateId

        /// <summary>
        /// Child Points where [Point].[YCoordinateId] point to this entity (FK_dbo.Point_dbo.Coordinate_YCoordinateId)
        /// </summary>
        public ICollection<Point> Points_YCoordinateId { get; set; } // Point.FK_dbo.Point_dbo.Coordinate_YCoordinateId

        public Coordinate()
        {
            Points_XCoordinateId = new List<Point>();
            Points_YCoordinateId = new List<Point>();
        }
    }

}
// </auto-generated>
