// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // EmptyTable
    public class EmptyTable
    {
        public int Id { get; set; } // Id (Primary key)
    }

}
// </auto-generated>
