// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Point
    public class Point
    {
        public int XCoordinateId { get; set; } // XCoordinateId (Primary key)
        public int YCoordinateId { get; set; } // YCoordinateId (Primary key)
        public double Value { get; set; } // Value

        // Foreign keys

        /// <summary>
        /// Parent Coordinate pointed by [Point].([XCoordinateId]) (FK_dbo.Point_dbo.Coordinate_XCoordinateId)
        /// </summary>
        public Coordinate XCoordinate { get; set; } // FK_dbo.Point_dbo.Coordinate_XCoordinateId

        /// <summary>
        /// Parent Coordinate pointed by [Point].([YCoordinateId]) (FK_dbo.Point_dbo.Coordinate_YCoordinateId)
        /// </summary>
        public Coordinate YCoordinate { get; set; } // FK_dbo.Point_dbo.Coordinate_YCoordinateId
    }

}
// </auto-generated>
