// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // ReservedSqlKeyword
    public class ReservedSqlKeyword
    {
        public int Id { get; set; } // Id (Primary key)
        public int? Key { get; set; } // Key
        public int? Identity { get; set; } // Identity
        public string Select { get; set; } // Select
    }

}
// </auto-generated>
