// <auto-generated />
namespace Tanneryd.BulkOperations.EF6.Tests.Migrations.School
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AddComputedFullNameColumnToInstructor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddComputedFullNameColumnToInstructor));
        
        string IMigrationMetadata.Id
        {
            get { return "201901131912134_AddComputedFullNameColumnToInstructor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
