// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // BatchInvoice
    public class BatchInvoiceConfiguration : IEntityTypeConfiguration<BatchInvoice>
    {
        public void Configure(EntityTypeBuilder<BatchInvoice> builder)
        {
            builder.ToTable("BatchInvoice", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_dbo.BatchInvoice").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"PrimaryKey").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
        }
    }

}
// </auto-generated>
