// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // CoachWithUserGeneratedGuid
    public class CoachWithUserGeneratedGuidConfiguration : IEntityTypeConfiguration<CoachWithUserGeneratedGuid>
    {
        public void Configure(EntityTypeBuilder<CoachWithUserGeneratedGuid> builder)
        {
            builder.ToTable("CoachWithUserGeneratedGuid", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_dbo.CoachWithUserGeneratedGuid").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Firstname).HasColumnName(@"Firstname").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.Lastname).HasColumnName(@"Lastname").HasColumnType("nvarchar(max)").IsRequired();
        }
    }

}
// </auto-generated>
