// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // CoachTeamsWithUserGeneratedGuid
    public class CoachTeamsWithUserGeneratedGuidConfiguration : IEntityTypeConfiguration<CoachTeamsWithUserGeneratedGuid>
    {
        public void Configure(EntityTypeBuilder<CoachTeamsWithUserGeneratedGuid> builder)
        {
            builder.ToTable("CoachTeamsWithUserGeneratedGuid", "dbo");
            builder.HasKey(x => new { x.CoachId, x.TeamId }).HasName("PK_dbo.CoachTeamsWithUserGeneratedGuid").IsClustered();

            builder.Property(x => x.CoachId).HasColumnName(@"CoachId").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.TeamId).HasColumnName(@"TeamId").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();

            // Foreign keys
            builder.HasOne(a => a.CoachWithUserGeneratedGuid).WithMany(b => b.CoachTeamsWithUserGeneratedGuids).HasForeignKey(c => c.CoachId).HasConstraintName("FK_dbo.CoachTeamsWithUserGeneratedGuid_dbo.CoachWithUserGeneratedGuid_CoachId");
            builder.HasOne(a => a.TeamWithUserGeneratedGuid).WithMany(b => b.CoachTeamsWithUserGeneratedGuids).HasForeignKey(c => c.TeamId).HasConstraintName("FK_dbo.CoachTeamsWithUserGeneratedGuid_dbo.TeamWithUserGeneratedGuid_TeamId");

            builder.HasIndex(x => x.CoachId).HasName("IX_CoachId");
            builder.HasIndex(x => x.TeamId).HasName("IX_TeamId");
        }
    }

}
// </auto-generated>
