// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // CoachWithDbGeneratedGuid
    public class CoachWithDbGeneratedGuidConfiguration : IEntityTypeConfiguration<CoachWithDbGeneratedGuid>
    {
        public void Configure(EntityTypeBuilder<CoachWithDbGeneratedGuid> builder)
        {
            builder.ToTable("CoachWithDbGeneratedGuid", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_dbo.CoachWithDbGeneratedGuid").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.Firstname).HasColumnName(@"Firstname").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.Lastname).HasColumnName(@"Lastname").HasColumnType("nvarchar(max)").IsRequired();
        }
    }

}
// </auto-generated>
