// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Person
    public class ContactConfiguration : IEntityTypeConfiguration<Contact>
    {
        public void Configure(EntityTypeBuilder<Contact> builder)
        {
            builder.HasNoKey();
            builder.ToView("Contact", "dbo");
            builder.Property(x => x.FirstName).HasColumnName(@"FirstName").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.LastName).HasColumnName(@"LastName").HasColumnType("nvarchar(max)").IsRequired();
        }
    }

}
// </auto-generated>
