// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // CourseInstructor
    public class CourseInstructorConfiguration : IEntityTypeConfiguration<CourseInstructor>
    {
        public void Configure(EntityTypeBuilder<CourseInstructor> builder)
        {
            builder.ToTable("CourseInstructor", "dbo");
            builder.HasKey(x => new { x.CourseId, x.InstructorId }).HasName("PK_dbo.CourseInstructor").IsClustered();

            builder.Property(x => x.CourseId).HasColumnName(@"CourseID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.InstructorId).HasColumnName(@"InstructorID").HasColumnType("int").IsRequired().ValueGeneratedNever();

            // Foreign keys
            builder.HasOne(a => a.Course).WithMany(b => b.CourseInstructors).HasForeignKey(c => c.CourseId).HasConstraintName("FK_dbo.CourseInstructor_dbo.Course_CourseID");
            builder.HasOne(a => a.Instructor).WithMany(b => b.CourseInstructors).HasForeignKey(c => c.InstructorId).HasConstraintName("FK_dbo.CourseInstructor_dbo.Instructor_InstructorID");

            builder.HasIndex(x => x.CourseId).HasName("IX_CourseID");
            builder.HasIndex(x => x.InstructorId).HasName("IX_InstructorID");
        }
    }

}
// </auto-generated>
