// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Department
    public class DepartmentConfiguration : IEntityTypeConfiguration<Department>
    {
        public void Configure(EntityTypeBuilder<Department> builder)
        {
            builder.ToTable("Department", "dbo");
            builder.HasKey(x => x.DepartmentId).HasName("PK_dbo.Department").IsClustered();

            builder.Property(x => x.DepartmentId).HasColumnName(@"DepartmentID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.Budget).HasColumnName(@"Budget").HasColumnType("decimal(18,2)").IsRequired();
            builder.Property(x => x.Administrator).HasColumnName(@"Administrator").HasColumnType("int").IsRequired(false);
        }
    }

}
// </auto-generated>
