// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Employee
    public class EmployeeConfiguration : IEntityTypeConfiguration<Employee>
    {
        public void Configure(EntityTypeBuilder<Employee> builder)
        {
            builder.ToTable("Employee", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_dbo.Employee").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("bigint").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.EmployerId).HasColumnName(@"EmployerId").HasColumnType("bigint").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Company).WithMany(b => b.Employees).HasForeignKey(c => c.EmployerId).HasConstraintName("FK_dbo.Employee_dbo.Company_EmployerId");

            builder.HasIndex(x => x.EmployerId).HasName("IX_EmployerId");
        }
    }

}
// </auto-generated>
