// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Invoice
    public class InvoiceConfiguration : IEntityTypeConfiguration<Invoice>
    {
        public void Configure(EntityTypeBuilder<Invoice> builder)
        {
            builder.ToTable("Invoice", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_dbo.Invoice").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"PrimaryKey").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Net).HasColumnName(@"Net").HasColumnType("decimal(18,2)").IsRequired();
            builder.Property(x => x.Gross).HasColumnName(@"Gross").HasColumnType("decimal(18,2)").IsRequired();
            builder.Property(x => x.Tax).HasColumnName(@"Tax").HasColumnType("decimal(19,2)").IsRequired().ValueGeneratedOnAddOrUpdate();
        }
    }

}
// </auto-generated>
