// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Keyword
    public class KeywordConfiguration : IEntityTypeConfiguration<Keyword>
    {
        public void Configure(EntityTypeBuilder<Keyword> builder)
        {
            builder.ToTable("Keyword", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_dbo.Keyword").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.PostId).HasColumnName(@"PostId").HasColumnType("uniqueidentifier").IsRequired();
            builder.Property(x => x.Text).HasColumnName(@"Text").HasColumnType("nvarchar(max)").IsRequired();

            // Foreign keys
            builder.HasOne(a => a.Post).WithMany(b => b.Keywords).HasForeignKey(c => c.PostId).HasConstraintName("FK_dbo.Keyword_dbo.Post_PostId");

            builder.HasIndex(x => x.PostId).HasName("IX_PostId");
        }
    }

}
// </auto-generated>
