// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // LogItem
    public class LogItemConfiguration : IEntityTypeConfiguration<LogItem>
    {
        public void Configure(EntityTypeBuilder<LogItem> builder)
        {
            builder.ToTable("LogItem", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_dbo.LogItem").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Message).HasColumnName(@"Message").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.Timestamp).HasColumnName(@"Timestamp").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.Severity).HasColumnName(@"Severity").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Recommendation).HasColumnName(@"Recommendation").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.LogType).HasColumnName(@"LogType").HasColumnType("nvarchar(128)").IsRequired(false).HasMaxLength(128);
        }
    }

}
// </auto-generated>
