// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // OfficeAssignment
    public class OfficeAssignmentConfiguration : IEntityTypeConfiguration<OfficeAssignment>
    {
        public void Configure(EntityTypeBuilder<OfficeAssignment> builder)
        {
            builder.ToTable("OfficeAssignment", "dbo");
            builder.HasKey(x => x.InstructorId).HasName("PK_dbo.OfficeAssignment").IsClustered();

            builder.Property(x => x.InstructorId).HasColumnName(@"InstructorID").HasColumnType("int").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Location).HasColumnName(@"Location").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.Timestamp).HasColumnName(@"Timestamp").HasColumnType("varbinary(max)").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.Instructor).WithOne(b => b.OfficeAssignment).HasForeignKey<OfficeAssignment>(c => c.InstructorId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_dbo.OfficeAssignment_dbo.Instructor_InstructorID");

            builder.HasIndex(x => x.InstructorId).HasName("IX_InstructorID");
        }
    }

}
// </auto-generated>
