// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Parity
    public class ParityConfiguration : IEntityTypeConfiguration<Parity>
    {
        public void Configure(EntityTypeBuilder<Parity> builder)
        {
            builder.ToTable("Parity", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_dbo.Parity").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Key").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(max)").IsRequired();
            builder.Property(x => x.UpdatedAt).HasColumnName(@"UpdatedAt").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("nvarchar(max)").IsRequired(false);
        }
    }

}
// </auto-generated>
