// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Prime
    public class PrimeConfiguration : IEntityTypeConfiguration<Prime>
    {
        public void Configure(EntityTypeBuilder<Prime> builder)
        {
            builder.ToTable("Prime", "dbo");
            builder.HasKey(x => x.NumberId).HasName("PK_dbo.Prime").IsClustered();

            builder.Property(x => x.NumberId).HasColumnName(@"NumberId").HasColumnType("bigint").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.UpdatedAt).HasColumnName(@"UpdatedAt").HasColumnType("datetime").IsRequired();
            builder.Property(x => x.UpdatedBy).HasColumnName(@"UpdatedBy").HasColumnType("nvarchar(max)").IsRequired(false);

            // Foreign keys
            builder.HasOne(a => a.Number).WithOne(b => b.Prime).HasForeignKey<Prime>(c => c.NumberId).OnDelete(DeleteBehavior.ClientSetNull).HasConstraintName("FK_dbo.Prime_dbo.Number_NumberId");

            builder.HasIndex(x => x.NumberId).HasName("IX_NumberId");
        }
    }

}
// </auto-generated>
