// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // ReservedSqlKeyword
    public class ReservedSqlKeywordConfiguration : IEntityTypeConfiguration<ReservedSqlKeyword>
    {
        public void Configure(EntityTypeBuilder<ReservedSqlKeyword> builder)
        {
            builder.ToTable("ReservedSqlKeyword", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_dbo.ReservedSqlKeyword").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Key).HasColumnName(@"Key").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Identity).HasColumnName(@"Identity").HasColumnType("int").IsRequired(false);
            builder.Property(x => x.Select).HasColumnName(@"Select").HasColumnType("nvarchar(max)").IsRequired(false);
        }
    }

}
// </auto-generated>
