// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // SummaryReportFROMTableASExtent
    public class SummaryReportFromTableAsExtentConfiguration : IEntityTypeConfiguration<SummaryReportFromTableAsExtent>
    {
        public void Configure(EntityTypeBuilder<SummaryReportFromTableAsExtent> builder)
        {
            builder.ToTable("SummaryReportFROMTableASExtent", "dbo");
            builder.HasKey(x => x.ReportId).HasName("PK_dbo.SummaryReportFROMTableASExtent").IsClustered();

            builder.Property(x => x.ReportId).HasColumnName(@"ReportID").HasColumnType("int").IsRequired().ValueGeneratedOnAdd().UseIdentityColumn();
            builder.Property(x => x.Title).HasColumnName(@"Title").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.Entry).HasColumnName(@"Entry").HasColumnType("nvarchar(max)").IsRequired(false);
            builder.Property(x => x.Volume).HasColumnName(@"Volume").HasColumnType("decimal(18,2)").IsRequired();
            builder.Property(x => x.Amount).HasColumnName(@"Amount").HasColumnType("decimal(18,2)").IsRequired();
            builder.Property(x => x.PeriodId).HasColumnName(@"PeriodID").HasColumnType("int").IsRequired();

            builder.HasIndex(x => x.PeriodId).HasName("IX_PeriodID");
        }
    }

}
// </auto-generated>
