// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // TeamWithUserGeneratedGuid
    public class TeamWithUserGeneratedGuidConfiguration : IEntityTypeConfiguration<TeamWithUserGeneratedGuid>
    {
        public void Configure(EntityTypeBuilder<TeamWithUserGeneratedGuid> builder)
        {
            builder.ToTable("TeamWithUserGeneratedGuid", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_dbo.TeamWithUserGeneratedGuid").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(max)").IsRequired();
        }
    }

}
// </auto-generated>
