// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // TeamWithDbGeneratedGuid
    public class TeamWithDbGeneratedGuidConfiguration : IEntityTypeConfiguration<TeamWithDbGeneratedGuid>
    {
        public void Configure(EntityTypeBuilder<TeamWithDbGeneratedGuid> builder)
        {
            builder.ToTable("TeamWithDbGeneratedGuid", "dbo");
            builder.HasKey(x => x.Id).HasName("PK_dbo.TeamWithDbGeneratedGuid").IsClustered();

            builder.Property(x => x.Id).HasColumnName(@"Id").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedOnAdd();
            builder.Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar(max)").IsRequired();
        }
    }

}
// </auto-generated>
