// <auto-generated>
// ReSharper disable All

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // VisitorPosts
    public class VisitorPostConfiguration : IEntityTypeConfiguration<VisitorPost>
    {
        public void Configure(EntityTypeBuilder<VisitorPost> builder)
        {
            builder.ToTable("VisitorPosts", "dbo");
            builder.HasKey(x => new { x.VisitorId, x.PostId }).HasName("PK_dbo.VisitorPosts").IsClustered();

            builder.Property(x => x.VisitorId).HasColumnName(@"VisitorId").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();
            builder.Property(x => x.PostId).HasColumnName(@"PostId").HasColumnType("uniqueidentifier").IsRequired().ValueGeneratedNever();

            // Foreign keys
            builder.HasOne(a => a.Post).WithMany(b => b.VisitorPosts).HasForeignKey(c => c.PostId).HasConstraintName("FK_dbo.VisitorPosts_dbo.Post_PostId");
            builder.HasOne(a => a.Visitor).WithMany(b => b.VisitorPosts).HasForeignKey(c => c.VisitorId).HasConstraintName("FK_dbo.VisitorPosts_dbo.Visitor_VisitorId");

            builder.HasIndex(x => x.PostId).HasName("IX_PostId");
            builder.HasIndex(x => x.VisitorId).HasName("IX_VisitorId");
        }
    }

}
// </auto-generated>
