// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Employee
    public class Employee
    {
        public long Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name
        public long EmployerId { get; set; } // EmployerId

        // Foreign keys

        /// <summary>
        /// Parent Company pointed by [Employee].([EmployerId]) (FK_dbo.Employee_dbo.Company_EmployerId)
        /// </summary>
        public Company Company { get; set; } // FK_dbo.Employee_dbo.Company_EmployerId
    }

}
// </auto-generated>
