// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Composite
    public class Composite
    {
        public long NumberId { get; set; } // NumberId (Primary key)
        public DateTime UpdatedAt { get; set; } // UpdatedAt
        public string UpdatedBy { get; set; } // UpdatedBy

        // Reverse navigation (pure many-to-many, matches EF6)
        public ICollection<Prime> Primes { get; set; }

        // Foreign keys
        public Number Number { get; set; }

        public Composite()
        {
            Primes = new HashSet<Prime>();
        }
    }
}
// </auto-generated>
