// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Number
    public class Number
    {
        public long Id { get; set; } // Id (Primary key)
        public long Value { get; set; } // Value
        public int ParityId { get; set; } // ParityId
        public int? PrimeId { get; set; } // PrimeId
        public int? CompositeId { get; set; } // CompositeId
        public DateTime UpdatedAt { get; set; } // UpdatedAt
        public string UpdatedBy { get; set; } // UpdatedBy

        // Reverse navigation

        /// <summary>
        /// Parent (One-to-One) Number pointed by [Composite].[NumberId] (FK_dbo.Composite_dbo.Number_NumberId)
        /// </summary>
        public Composite Composite { get; set; } // Composite.FK_dbo.Composite_dbo.Number_NumberId

        /// <summary>
        /// Parent (One-to-One) Number pointed by [Prime].[NumberId] (FK_dbo.Prime_dbo.Number_NumberId)
        /// </summary>
        public Prime Prime { get; set; } // Prime.FK_dbo.Prime_dbo.Number_NumberId

        // Foreign keys

        /// <summary>
        /// Parent Parity pointed by [Number].([ParityId]) (FK_dbo.Number_dbo.Parity_ParityId)
        /// </summary>
        public Parity Parity { get; set; } // FK_dbo.Number_dbo.Parity_ParityId
    }

}
// </auto-generated>
