// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Prime
    public class Prime
    {
        public long NumberId { get; set; } // NumberId (Primary key)
        public DateTime UpdatedAt { get; set; } // UpdatedAt
        public string UpdatedBy { get; set; } // UpdatedBy

        // Reverse navigation (pure many-to-many, matches EF6)
        public ICollection<Composite> Composites { get; set; }

        // Foreign keys
        public Number Number { get; set; }

        public Prime()
        {
            Composites = new HashSet<Composite>();
        }
    }
}
// </auto-generated>
