//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tanneryd.BulkOperations.EF6.NET47.ModelFirst.Tests.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BatchInvoiceItem
    {
        public System.Guid Id { get; set; }
        public System.Guid BatchInvoiceId { get; set; }
        public System.Guid InvoiceId { get; set; }
    
        public virtual BatchInvoice BatchInvoice { get; set; }
        public virtual Invoice Invoice { get; set; }
    }
}
