//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tanneryd.BulkOperations.EF6.NET47.ModelFirst.Tests.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Number
    {
        public long Id { get; set; }
        public long Value { get; set; }
        public int ParityId { get; set; }
        public Nullable<int> PrimeId { get; set; }
        public Nullable<int> CompositeId { get; set; }
        public System.DateTime UpdatedAt { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Composite Composite { get; set; }
        public virtual Parity Parity { get; set; }
        public virtual Prime Prime { get; set; }
    }
}
