//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tanneryd.BulkOperations.EF6.NET47.ModelFirst.Tests.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerWithDbGeneratedGuid
    {
        public System.Guid Id { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public System.Guid TeamId { get; set; }
    
        public virtual TeamWithDbGeneratedGuidKey TeamWithDbGeneratedGuid { get; set; }
    }
}
