//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tanneryd.BulkOperations.EF6.NET47.ModelFirst.Tests.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Point
    {
        public int XCoordinateId { get; set; }
        public int YCoordinateId { get; set; }
        public double Value { get; set; }
    
        public virtual Coordinate XCoordinate { get; set; }
        public virtual Coordinate YCoordinate { get; set; }
    }
}
