//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tanneryd.BulkOperations.EF6.NET47.ModelFirst.Tests.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReservedSqlKeyword
    {
        public int Id { get; set; }
        public Nullable<int> Key { get; set; }
        public Nullable<int> Identity { get; set; }
        public string Select { get; set; }
    }
}
