//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tanneryd.BulkOperations.EF6.NET47.ModelFirst.Tests.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SELECT_WORSE_FROM_NAMES_AS_Extent1
    {
        public int ReportID { get; set; }
        public string Title { get; set; }
        public string Entry { get; set; }
        public System.DateTime Date { get; set; }
        public string Level1 { get; set; }
        public string Level2 { get; set; }
        public string Level3 { get; set; }
        public string I_am_Bad_Column_Name_1_ { get; set; }
        public string A_____Abc_123_Абв_ { get; set; }
        public string SELECT_WORSE_FROM_NAMES_AS_Extent_ { get; set; }
        public decimal Volume { get; set; }
        public decimal Amount { get; set; }
        public int PeriodID { get; set; }
        public int SummaryReportID { get; set; }
    
        public virtual SummaryReportFROMTableASExtent SummaryReportFROMTableASExtent { get; set; }
        public virtual Period Period { get; set; }
    }
}
