//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tanneryd.BulkOperations.EF6.NET47.ModelFirst.Tests.Models.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class SummaryReportFROMTableASExtent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SummaryReportFROMTableASExtent()
        {
            this.SELECT_WORSE_FROM_NAMES_AS_Extent1 = new HashSet<SELECT_WORSE_FROM_NAMES_AS_Extent1>();
        }
    
        public int ReportID { get; set; }
        public string Title { get; set; }
        public string Entry { get; set; }
        public decimal Volume { get; set; }
        public decimal Amount { get; set; }
        public int PeriodID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SELECT_WORSE_FROM_NAMES_AS_Extent1> SELECT_WORSE_FROM_NAMES_AS_Extent1 { get; set; }
        public virtual Period Period { get; set; }
    }
}
