//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tanneryd.BulkOperations.EF6.NET47.ModelFirst.Tests.Models.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UnitTestsContext : DbContext
    {
        public UnitTestsContext()
            : base("name=UnitTestsContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BatchInvoice> BatchInvoices { get; set; }
        public virtual DbSet<BatchInvoiceItem> BatchInvoiceItems { get; set; }
        public virtual DbSet<Blog> Blogs { get; set; }
        public virtual DbSet<CoachWithDbGeneratedGuidKey> CoachesWithDbGeneratedGuids { get; set; }
        public virtual DbSet<CoachWithUserGeneratedGuidKey> CoachesWithUserGeneratedGuids { get; set; }
        public virtual DbSet<Company> Companies { get; set; }
        public virtual DbSet<Composite> Composites { get; set; }
        public virtual DbSet<Coordinate> Coordinates { get; set; }
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<EmptyTable> EmptyTables { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<Invoice> Invoices { get; set; }
        public virtual DbSet<InvoiceItem> InvoiceItems { get; set; }
        public virtual DbSet<Journal> Journals { get; set; }
        public virtual DbSet<Keyword> Keywords { get; set; }
        public virtual DbSet<Level1> Levels { get; set; }
        public virtual DbSet<LogItem> LogItems { get; set; }
        public virtual DbSet<Number> Numbers { get; set; }
        public virtual DbSet<OfficeAssignment> OfficeAssignments { get; set; }
        public virtual DbSet<Parity> Parities { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<PlayerWithDbGeneratedGuid> PlayerWithDbGeneratedGuids { get; set; }
        public virtual DbSet<PlayerWithUserGeneratedGuid> PlayerWithUserGeneratedGuids { get; set; }
        public virtual DbSet<Point> Points { get; set; }
        public virtual DbSet<Post> Posts { get; set; }
        public virtual DbSet<Price> Prices { get; set; }
        public virtual DbSet<Prime> Primes { get; set; }
        public virtual DbSet<ReservedSqlKeyword> ReservedSqlKeywords { get; set; }
        public virtual DbSet<SummaryReportFROMTableASExtent> SummaryReportFROMTableASExtents { get; set; }
        public virtual DbSet<TeamWithDbGeneratedGuidKey> TeamsWithDbGeneratedGuids { get; set; }
        public virtual DbSet<TeamWithUserGeneratedGuidKey> TeamsWithUserGeneratedGuids { get; set; }
        public virtual DbSet<Visitor> Visitors { get; set; }
        public virtual DbSet<SELECT_WORSE_FROM_NAMES_AS_Extent1> SELECT_WORSE_FROM_NAMES_AS_Extent1 { get; set; }
        public virtual DbSet<Period> Periods { get; set; }
    }
}
