// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // CoachTeamsWithUserGeneratedGuid
    public class CoachTeamsWithUserGeneratedGuid
    {
        public Guid CoachId { get; set; } // CoachId (Primary key)
        public Guid TeamId { get; set; } // TeamId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent CoachWithUserGeneratedGuid pointed by [CoachTeamsWithUserGeneratedGuid].([CoachId]) (FK_dbo.CoachTeamsWithUserGeneratedGuid_dbo.CoachWithUserGeneratedGuid_CoachId)
        /// </summary>
        public CoachWithUserGeneratedGuid CoachWithUserGeneratedGuid { get; set; } // FK_dbo.CoachTeamsWithUserGeneratedGuid_dbo.CoachWithUserGeneratedGuid_CoachId

        /// <summary>
        /// Parent TeamWithUserGeneratedGuid pointed by [CoachTeamsWithUserGeneratedGuid].([TeamId]) (FK_dbo.CoachTeamsWithUserGeneratedGuid_dbo.TeamWithUserGeneratedGuid_TeamId)
        /// </summary>
        public TeamWithUserGeneratedGuid TeamWithUserGeneratedGuid { get; set; } // FK_dbo.CoachTeamsWithUserGeneratedGuid_dbo.TeamWithUserGeneratedGuid_TeamId
    }

}
// </auto-generated>
