// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // CoachWithUserGeneratedGuid
    public class CoachWithUserGeneratedGuid
    {
        public Guid Id { get; set; } // Id (Primary key)
        public string Firstname { get; set; } // Firstname
        public string Lastname { get; set; } // Lastname

        // Reverse navigation (pure many-to-many, matches EF6)
        public ICollection<TeamWithUserGeneratedGuid> Teams { get; set; }

        public CoachWithUserGeneratedGuid()
        {
            Teams = new List<TeamWithUserGeneratedGuid>();
        }
    }
}
// </auto-generated>
