// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // TeamWithUserGeneratedGuid
    public class TeamWithUserGeneratedGuid
    {
        public Guid Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name

        // Reverse navigation
        public ICollection<PlayerWithUserGeneratedGuid> PlayerWithUserGeneratedGuids { get; set; }

        public TeamWithUserGeneratedGuid()
        {
            PlayerWithUserGeneratedGuids = new List<PlayerWithUserGeneratedGuid>();
        }
    }
}
// </auto-generated>
