// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // TeamWithUserGeneratedGuid
    public class TeamWithUserGeneratedGuid
    {
        public Guid Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name

        // Reverse navigation

        /// <summary>
        /// Child CoachTeamsWithUserGeneratedGuids where [CoachTeamsWithUserGeneratedGuid].[TeamId] point to this entity (FK_dbo.CoachTeamsWithUserGeneratedGuid_dbo.TeamWithUserGeneratedGuid_TeamId)
        /// </summary>
        public ICollection<CoachTeamsWithUserGeneratedGuid> CoachTeamsWithUserGeneratedGuids { get; set; } // CoachTeamsWithUserGeneratedGuid.FK_dbo.CoachTeamsWithUserGeneratedGuid_dbo.TeamWithUserGeneratedGuid_TeamId

        /// <summary>
        /// Child PlayerWithUserGeneratedGuids where [PlayerWithUserGeneratedGuid].[TeamId] point to this entity (FK_dbo.PlayerWithUserGeneratedGuid_dbo.TeamWithUserGeneratedGuid_TeamId)
        /// </summary>
        public ICollection<PlayerWithUserGeneratedGuid> PlayerWithUserGeneratedGuids { get; set; } // PlayerWithUserGeneratedGuid.FK_dbo.PlayerWithUserGeneratedGuid_dbo.TeamWithUserGeneratedGuid_TeamId

        public TeamWithUserGeneratedGuid()
        {
            CoachTeamsWithUserGeneratedGuids = new List<CoachTeamsWithUserGeneratedGuid>();
            PlayerWithUserGeneratedGuids = new List<PlayerWithUserGeneratedGuid>();
        }
    }

}
// </auto-generated>
