// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // SummaryReportFROMTableASExtent
    public class SummaryReportFromTableAsExtent
    {
        public int ReportId { get; set; } // ReportID (Primary key)
        public string Title { get; set; } // Title
        public string Entry { get; set; } // Entry
        public decimal Volume { get; set; } // Volume
        public decimal Amount { get; set; } // Amount
        public int PeriodId { get; set; } // PeriodID
    }

}
// </auto-generated>
