// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Person
    public class Person
    {
        public long Id { get; set; } // Id (Primary key)
        public string FirstName { get; set; } // FirstName
        public string LastName { get; set; } // LastName
        public DateTime BirthDate { get; set; } // BirthDate
        public long? MotherId { get; set; } // MotherId
        public int? EmployeeNumber { get; set; } // EmployeeNumber

        // Reverse navigation

        /// <summary>
        /// Child People where [Person].[MotherId] point to this entity (FK_dbo.Person_dbo.Person_MotherId)
        /// </summary>
        public ICollection<Person> People { get; set; } // Person.FK_dbo.Person_dbo.Person_MotherId

        // Foreign keys

        /// <summary>
        /// Parent Person pointed by [Person].([MotherId]) (FK_dbo.Person_dbo.Person_MotherId)
        /// </summary>
        public Person Mother { get; set; } // FK_dbo.Person_dbo.Person_MotherId

        public Person()
        {
            People = new List<Person>();
        }
    }

}
// </auto-generated>
