// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Blog
    public class Blog
    {
        public Guid Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name

        // Reverse navigation

        /// <summary>
        /// Child Posts where [Post].[BlogId] point to this entity (FK_dbo.Post_dbo.Blog_BlogId)
        /// </summary>
        public ICollection<Post> Posts { get; set; } // Post.FK_dbo.Post_dbo.Blog_BlogId

        public Blog()
        {
            Id = Guid.NewGuid();
            Posts = new List<Post>();
        }
    }

}
// </auto-generated>
