// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Post
    public class Post
    {
        public Guid Id { get; set; } // Id (Primary key)
        public Guid BlogId { get; set; } // BlogId
        public string Text { get; set; } // Text

        // Reverse navigation

        /// <summary>
        /// Child Keywords where [Keyword].[PostId] point to this entity (FK_dbo.Keyword_dbo.Post_PostId)
        /// </summary>
        public ICollection<Keyword> Keywords { get; set; } // Keyword.FK_dbo.Keyword_dbo.Post_PostId

        /// <summary>
        /// Child VisitorPosts where [VisitorPosts].[PostId] point to this entity (FK_dbo.VisitorPosts_dbo.Post_PostId)
        /// </summary>
        public ICollection<VisitorPost> VisitorPosts { get; set; } // VisitorPosts.FK_dbo.VisitorPosts_dbo.Post_PostId
        public ICollection<Visitor> Visitors { get; set; }
        // Foreign keys

        /// <summary>
        /// Parent Blog pointed by [Post].([BlogId]) (FK_dbo.Post_dbo.Blog_BlogId)
        /// </summary>
        public Blog Blog { get; set; } // FK_dbo.Post_dbo.Blog_BlogId

        public Post()
        {
            Id = Guid.NewGuid();
            Keywords = new List<Keyword>();
            VisitorPosts = new List<VisitorPost>();
            Visitors = new List<Visitor>();
        }
    }

}
// </auto-generated>
