// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Post
    public class Post
    {
        public Guid Id { get; set; } // Id (Primary key)
        public Guid BlogId { get; set; } // BlogId
        public string Text { get; set; } // Text

        // Reverse navigation
        public ICollection<Keyword> Keywords { get; set; }
        public ICollection<Visitor> Visitors { get; set; }

        // Foreign keys
        public Blog Blog { get; set; }

        public Post()
        {
            Id = Guid.NewGuid();
            Keywords = new List<Keyword>();
            Visitors = new List<Visitor>();
        }
    }
}
// </auto-generated>
