// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Visitor
    public class Visitor
    {
        public Guid Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name

        // Reverse navigation
        public ICollection<Post> Posts { get; set; }

        public Visitor()
        {
            Id = Guid.NewGuid();
            Posts = new List<Post>();
        }
    }
}
// </auto-generated>
