// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // VisitorPosts
    public class VisitorPost
    {
        public Guid VisitorId { get; set; } // VisitorId (Primary key)
        public Guid PostId { get; set; } // PostId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent Post pointed by [VisitorPosts].([PostId]) (FK_dbo.VisitorPosts_dbo.Post_PostId)
        /// </summary>
        public Post Post { get; set; } // FK_dbo.VisitorPosts_dbo.Post_PostId

        /// <summary>
        /// Parent Visitor pointed by [VisitorPosts].([VisitorId]) (FK_dbo.VisitorPosts_dbo.Visitor_VisitorId)
        /// </summary>
        public Visitor Visitor { get; set; } // FK_dbo.VisitorPosts_dbo.Visitor_VisitorId
    }

}
// </auto-generated>
