// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // CoachWithDbGeneratedGuid
    public class CoachWithDbGeneratedGuid
    {
        public Guid Id { get; set; } // Id (Primary key)
        public string Firstname { get; set; } // Firstname
        public string Lastname { get; set; } // Lastname

        // Reverse navigation

        /// <summary>
        /// Child CoachTeamsWithDbGeneratedGuids where [CoachTeamsWithDbGeneratedGuid].[CoachId] point to this entity (FK_dbo.CoachTeamsWithDbGeneratedGuid_dbo.CoachWithDbGeneratedGuid_CoachId)
        /// </summary>
        public ICollection<CoachTeamsWithDbGeneratedGuid> CoachTeamsWithDbGeneratedGuids { get; set; } // CoachTeamsWithDbGeneratedGuid.FK_dbo.CoachTeamsWithDbGeneratedGuid_dbo.CoachWithDbGeneratedGuid_CoachId
        
        [NotMapped]
        List<TeamWithDbGeneratedGuid> Teams
        {
            get
            {
                return CoachTeamsWithDbGeneratedGuids.Select(ct => ct.TeamWithDbGeneratedGuid).ToList();
            }
        }
        public CoachWithDbGeneratedGuid()
        {
            Id = Guid.NewGuid();
            CoachTeamsWithDbGeneratedGuids = new List<CoachTeamsWithDbGeneratedGuid>();
        }
    }

}
// </auto-generated>
