// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // CoachWithDbGeneratedGuid
    public class CoachWithDbGeneratedGuid
    {
        public Guid Id { get; set; } // Id (Primary key)
        public string Firstname { get; set; } // Firstname
        public string Lastname { get; set; } // Lastname

        // Reverse navigation (pure many-to-many, matches EF6)
        public ICollection<TeamWithDbGeneratedGuid> Teams { get; set; }

        public CoachWithDbGeneratedGuid()
        {
            Id = Guid.NewGuid();
            Teams = new List<TeamWithDbGeneratedGuid>();
        }
    }
}
// </auto-generated>
