// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // CoachTeamsWithDbGeneratedGuid
    public class CoachTeamsWithDbGeneratedGuid
    {
        public Guid CoachId { get; set; } // CoachId (Primary key)
        public Guid TeamId { get; set; } // TeamId (Primary key)

        // Foreign keys

        /// <summary>
        /// Parent CoachWithDbGeneratedGuid pointed by [CoachTeamsWithDbGeneratedGuid].([CoachId]) (FK_dbo.CoachTeamsWithDbGeneratedGuid_dbo.CoachWithDbGeneratedGuid_CoachId)
        /// </summary>
        public CoachWithDbGeneratedGuid CoachWithDbGeneratedGuid { get; set; } // FK_dbo.CoachTeamsWithDbGeneratedGuid_dbo.CoachWithDbGeneratedGuid_CoachId

        /// <summary>
        /// Parent TeamWithDbGeneratedGuid pointed by [CoachTeamsWithDbGeneratedGuid].([TeamId]) (FK_dbo.CoachTeamsWithDbGeneratedGuid_dbo.TeamWithDbGeneratedGuid_TeamId)
        /// </summary>
        public TeamWithDbGeneratedGuid TeamWithDbGeneratedGuid { get; set; } // FK_dbo.CoachTeamsWithDbGeneratedGuid_dbo.TeamWithDbGeneratedGuid_TeamId
    }

}
// </auto-generated>
