// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // PlayerWithDbGeneratedGuid
    public class PlayerWithDbGeneratedGuid
    {
        public Guid Id { get; set; } // Id (Primary key)
        public string Firstname { get; set; } // Firstname
        public string Lastname { get; set; } // Lastname
        public Guid TeamId { get; set; } // TeamId

        // Foreign keys

        /// <summary>
        /// Parent TeamWithDbGeneratedGuid pointed by [PlayerWithDbGeneratedGuid].([TeamId]) (FK_dbo.PlayerWithDbGeneratedGuid_dbo.TeamWithDbGeneratedGuid_TeamId)
        /// </summary>
        public TeamWithDbGeneratedGuid TeamWithDbGeneratedGuid { get; set; } // FK_dbo.PlayerWithDbGeneratedGuid_dbo.TeamWithDbGeneratedGuid_TeamId

        public PlayerWithDbGeneratedGuid()
        {
            Id = Guid.NewGuid();
        }
    }

}
// </auto-generated>
