// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // TeamWithDbGeneratedGuid
    public class TeamWithDbGeneratedGuid
    {
        public Guid Id { get; set; } // Id (Primary key)
        public string Name { get; set; } // Name

        // Reverse navigation
        public ICollection<PlayerWithDbGeneratedGuid> PlayerWithDbGeneratedGuids { get; set; }

        public TeamWithDbGeneratedGuid()
        {
            Id = Guid.NewGuid();
            PlayerWithDbGeneratedGuids = new List<PlayerWithDbGeneratedGuid>();
        }
    }
}
// </auto-generated>
