// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // LogItem
    public class LogItem
    {
        public int Id { get; set; } // Id (Primary key)
        public string Message { get; set; } // Message
        public DateTime Timestamp { get; set; } // Timestamp
        public int? Severity { get; set; } // Severity
        public string Recommendation { get; set; } // Recommendation
        public string LogType { get; set; } // LogType (length: 128)
    }

}
// </auto-generated>
