// <auto-generated>
// ReSharper disable All

using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;

namespace Tanneryd.BulkOperations.EFCore.Tests
{
    // Price
    public class Price
    {
        public int Id { get; set; } // Id (Primary key)
        public DateTime Date { get; set; } // Date
        public string Name { get; set; } // Name
        public decimal? Value { get; set; } // Value
    }

}
// </auto-generated>
